import httpx
import base64
from app.core.config import settings

# Spotify API base URLs
SPOTIFY_AUTH_URL = "https://accounts.spotify.com/authorize"
SPOTIFY_TOKEN_URL = "https://accounts.spotify.com/api/token"
SPOTIFY_API_URL = "https://api.spotify.com/v1"

# Permissions we request from the user's Spotify account.
# playlist-modify-public  = create public playlists
# playlist-modify-private = create private playlists
# user-read-private       = read user profile info
SPOTIFY_SCOPES = "playlist-modify-public playlist-modify-private user-read-private"


def get_spotify_auth_url(user_id: str) -> str:
    """
    Builds the Spotify OAuth2 authorization URL.
    We pass the user_id as "state" — Spotify sends it back in the
    callback so we know which user just connected their account.
    """
    params = {
        "client_id": settings.SPOTIFY_CLIENT_ID,
        "response_type": "code",
        "redirect_uri": settings.SPOTIFY_REDIRECT_URI,
        "scope": SPOTIFY_SCOPES,
        "state": user_id,
    }
    query = "&".join(f"{k}={v}" for k, v in params.items())
    return f"{SPOTIFY_AUTH_URL}?{query}"


async def exchange_code_for_tokens(code: str) -> dict:
    """
    Exchanges the authorization code received from Spotify
    for actual access and refresh tokens.
    This is step 2 of the OAuth2 flow.
    """
    # Spotify requires Basic Auth with client_id:client_secret encoded in base64
    credentials = f"{settings.SPOTIFY_CLIENT_ID}:{settings.SPOTIFY_CLIENT_SECRET}"
    encoded = base64.b64encode(credentials.encode()).decode()

    async with httpx.AsyncClient() as client:
        response = await client.post(
            SPOTIFY_TOKEN_URL,
            headers={
                "Authorization": f"Basic {encoded}",
                "Content-Type": "application/x-www-form-urlencoded",
            },
            data={
                "grant_type": "authorization_code",
                "code": code,
                "redirect_uri": settings.SPOTIFY_REDIRECT_URI,
            },
        )
        response.raise_for_status()
        return response.json()


async def refresh_spotify_token(refresh_token: str) -> str:
    """
    Spotify access tokens expire after 1 hour.
    Uses the refresh token to get a new access token
    without asking the user to log in again.
    """
    credentials = f"{settings.SPOTIFY_CLIENT_ID}:{settings.SPOTIFY_CLIENT_SECRET}"
    encoded = base64.b64encode(credentials.encode()).decode()

    async with httpx.AsyncClient() as client:
        response = await client.post(
            SPOTIFY_TOKEN_URL,
            headers={
                "Authorization": f"Basic {encoded}",
                "Content-Type": "application/x-www-form-urlencoded",
            },
            data={
                "grant_type": "refresh_token",
                "refresh_token": refresh_token,
            },
        )
        response.raise_for_status()
        data = response.json()
        # Spotify only returns a new access_token — refresh_token stays the same
        return data["access_token"]


async def get_valid_access_token(user) -> str:
    """
    Returns a valid Spotify access token for the given user.
    Automatically refreshes it if expired.
    Called before every Spotify API request.
    """
    try:
        # Try the stored access token first
        async with httpx.AsyncClient() as client:
            response = await client.get(
                f"{SPOTIFY_API_URL}/me",
                headers={"Authorization": f"Bearer {user.spotify_access_token}"},
            )
            if response.status_code == 200:
                return user.spotify_access_token
    except Exception:
        pass

    # Token expired — refresh it using the refresh token
    return await refresh_spotify_token(user.spotify_refresh_token)


async def create_spotify_playlist(
    access_token: str,
    spotify_user_id: str,
    name: str,
    track_uris: list[str],
) -> dict:
    """
    Creates a playlist on the user's Spotify account and fills it with tracks.
    Returns the playlist ID and shareable URL.
    """
    async with httpx.AsyncClient() as client:
        # Step 1: Create an empty playlist on the user's account
        create_response = await client.post(
            f"{SPOTIFY_API_URL}/users/{spotify_user_id}/playlists",
            headers={
                "Authorization": f"Bearer {access_token}",
                "Content-Type": "application/json",
            },
            json={
                "name": name,
                "description": "Generated by MoodQueue 🎵",
                "public": False,
            },
        )
        create_response.raise_for_status()
        playlist = create_response.json()

        # Step 2: Fill the playlist with tracks
        # Spotify accepts a maximum of 100 tracks per request
        if track_uris:
            await client.post(
                f"{SPOTIFY_API_URL}/playlists/{playlist['id']}/tracks",
                headers={
                    "Authorization": f"Bearer {access_token}",
                    "Content-Type": "application/json",
                },
                json={"uris": track_uris[:100]},
            )

        return {
            "spotify_playlist_id": playlist["id"],
            "spotify_playlist_url": playlist["external_urls"]["spotify"],
        }


async def search_tracks_by_mood(access_token: str, mood: str) -> list[str]:
    """
    Searches Spotify for tracks matching a given mood.
    Returns a list of track URIs (e.g. spotify:track:abc123).
    Mood labels are mapped to rich search keywords for better results.
    OpenAI will generate the mood label at step 6 — this function
    receives it and finds matching tracks.
    """

    # Rich mood-to-query mapping — covers a wide range of emotional states.
    # Each query is tuned to return relevant tracks on Spotify's search engine.
    mood_queries = {
        # Happy / positive
        "happy": "happy feel good upbeat pop",
        "joyful": "joyful euphoric celebration dance",
        "excited": "excited hype energy banger",
        "grateful": "grateful blessed positive vibes soul",

        # Sad / melancholic
        "sad": "sad heartbreak melancholic indie",
        "melancholic": "melancholic nostalgic rainy day piano",
        "lonely": "lonely empty solitude ambient",
        "heartbroken": "heartbreak breakup emotional ballad",

        # Calm / peaceful
        "calm": "calm peaceful ambient meditation",
        "relaxed": "relaxed chill lofi jazz",
        "sleepy": "sleep ambient drone soft piano",
        "peaceful": "peaceful nature acoustic guitar",

        # Energetic / intense
        "energetic": "energetic workout pump up high tempo",
        "angry": "angry aggressive metal hard rock",
        "motivated": "motivated gym grind hip hop",
        "powerful": "powerful epic orchestral cinematic",

        # Nostalgic / retro
        "nostalgic": "nostalgic throwback 90s classics",
        "retro": "retro vintage 80s synthwave",
        "sentimental": "sentimental memories slow oldies",

        # Romantic / social
        "romantic": "romantic love RnB slow jam",
        "flirty": "flirty smooth sensual groove",
        "heartwarming": "heartwarming wholesome acoustic folk",

        # Focus / work
        "focused": "focus deep work lofi concentration",
        "creative": "creative flow instrumental jazz",
        "studying": "study concentration classical piano",
        "productive": "productive morning routine uptempo",

        # Dark / introspective
        "dark": "dark moody atmospheric alternative",
        "anxious": "anxious tense cinematic strings",
        "reflective": "reflective introspective indie folk",
        "hopeful": "hopeful uplifting inspirational",

        # Party / social
        "party": "party dance club house",
        "summer": "summer beach vibes tropical",
        "confident": "confident swagger hip hop trap",
    }

    # Fall back to the raw mood label if not found in our map —
    # OpenAI might return a mood we haven't explicitly listed
    query = mood_queries.get(mood.lower(), mood)

    async with httpx.AsyncClient() as client:
        response = await client.get(
            f"{SPOTIFY_API_URL}/search",
            headers={"Authorization": f"Bearer {access_token}"},
            params={
                "q": query,
                "type": "track",
                "limit": 20,
            },
        )
        response.raise_for_status()
        data = response.json()

        # Extract track URIs from the response
        tracks = data.get("tracks", {}).get("items", [])
        return [track["uri"] for track in tracks if track.get("uri")]