import httpx
import base64
import asyncio
from app.core.config import settings

SPOTIFY_AUTH_URL = "https://accounts.spotify.com/authorize"
SPOTIFY_TOKEN_URL = "https://accounts.spotify.com/api/token"
SPOTIFY_API_URL = "https://api.spotify.com/v1"

SPOTIFY_SCOPES = "playlist-modify-public playlist-modify-private user-read-private user-read-email"


def get_spotify_auth_url(user_id: str) -> str:
    """
    Builds the Spotify OAuth2 authorization URL.
    show_dialog=true forces Spotify to show the permission screen again
    even if the user already granted access — ensures new scopes are applied.
    """
    params = {
        "client_id": settings.SPOTIFY_CLIENT_ID,
        "response_type": "code",
        "redirect_uri": settings.SPOTIFY_REDIRECT_URI,
        "scope": SPOTIFY_SCOPES,
        "state": user_id,
        "show_dialog": "true",
    }
    query = "&".join(f"{k}={v}" for k, v in params.items())
    return f"{SPOTIFY_AUTH_URL}?{query}"


async def exchange_code_for_tokens(code: str) -> dict:
    """
    Exchanges the authorization code received from Spotify
    for actual access and refresh tokens.
    """
    credentials = f"{settings.SPOTIFY_CLIENT_ID}:{settings.SPOTIFY_CLIENT_SECRET}"
    encoded = base64.b64encode(credentials.encode()).decode()

    async with httpx.AsyncClient() as client:
        response = await client.post(
            SPOTIFY_TOKEN_URL,
            headers={
                "Authorization": f"Basic {encoded}",
                "Content-Type": "application/x-www-form-urlencoded",
            },
            data={
                "grant_type": "authorization_code",
                "code": code,
                "redirect_uri": settings.SPOTIFY_REDIRECT_URI,
            },
        )
        response.raise_for_status()
        return response.json()


async def refresh_spotify_token(refresh_token: str) -> str:
    """
    Uses the refresh token to get a new access token
    without asking the user to log in again.
    """
    credentials = f"{settings.SPOTIFY_CLIENT_ID}:{settings.SPOTIFY_CLIENT_SECRET}"
    encoded = base64.b64encode(credentials.encode()).decode()

    async with httpx.AsyncClient() as client:
        response = await client.post(
            SPOTIFY_TOKEN_URL,
            headers={
                "Authorization": f"Basic {encoded}",
                "Content-Type": "application/x-www-form-urlencoded",
            },
            data={
                "grant_type": "refresh_token",
                "refresh_token": refresh_token,
            },
        )
        response.raise_for_status()
        data = response.json()
        return data["access_token"]


async def get_valid_access_token(user) -> str:
    """
    Returns a valid Spotify access token for the given user.
    Automatically refreshes it if expired.
    """
    try:
        async with httpx.AsyncClient() as client:
            response = await client.get(
                f"{SPOTIFY_API_URL}/me",
                headers={"Authorization": f"Bearer {user.spotify_access_token}"},
            )
            if response.status_code == 200:
                return user.spotify_access_token
    except Exception:
        pass

    return await refresh_spotify_token(user.spotify_refresh_token)


async def get_spotify_user_id(access_token: str) -> str:
    """
    Fetches the Spotify user ID for the authenticated user.
    """
    async with httpx.AsyncClient() as client:
        response = await client.get(
            f"{SPOTIFY_API_URL}/me",
            headers={"Authorization": f"Bearer {access_token}"},
        )
        response.raise_for_status()
        return response.json()["id"]


async def create_spotify_playlist(
    access_token: str,
    spotify_user_id: str,
    name: str,
    track_uris: list[str],
) -> dict:
    """
    Creates a private playlist and adds tracks.
    Adds a 1 second delay between creation and track addition —
    Spotify sometimes needs time before accepting modifications.
    """
    async with httpx.AsyncClient() as client:
        # Step 1: Create a private playlist
        create_response = await client.post(
            f"{SPOTIFY_API_URL}/me/playlists",
            headers={
                "Authorization": f"Bearer {access_token}",
                "Content-Type": "application/json",
            },
            json={
                "name": name,
                "description": "Generated by MoodQueue 🎵",
                "public": False,
                "collaborative": False,
            },
        )

        if create_response.status_code != 201:
            print(f"DEBUG playlist creation error: {create_response.status_code} - {create_response.text}")

        create_response.raise_for_status()
        playlist = create_response.json()
        print(f"DEBUG playlist created: {playlist['id']}")

        # Wait 1 second — Spotify sometimes needs time before
        # accepting track additions to a newly created playlist
        await asyncio.sleep(1)

        # Step 2: Add all tracks in one batch request
        if track_uris:
            add_response = await client.post(
                f"{SPOTIFY_API_URL}/playlists/{playlist['id']}/tracks",
                headers={
                    "Authorization": f"Bearer {access_token}",
                    "Content-Type": "application/json",
                },
                json={"uris": track_uris[:10]},
            )
            if add_response.status_code == 201:
                print(f"DEBUG added {len(track_uris[:10])} tracks successfully")
            else:
                print(f"DEBUG add tracks error: {add_response.status_code} - {add_response.text}")

        return {
            "spotify_playlist_id": playlist["id"],
            "spotify_playlist_url": playlist["external_urls"]["spotify"],
        }


async def search_tracks_by_mood(access_token: str, mood: str) -> list[str]:
    """
    Searches Spotify for tracks matching a given mood.
    Returns a list of track URIs (e.g. spotify:track:abc123).
    """
    mood_queries = {
        # Happy / positive
        "happy": "happy feel good upbeat pop",
        "joyful": "joyful euphoric celebration dance",
        "excited": "excited hype energy banger",
        "grateful": "grateful blessed positive vibes soul",

        # Sad / melancholic
        "sad": "sad heartbreak melancholic indie",
        "melancholic": "melancholic nostalgic rainy day piano",
        "lonely": "lonely empty solitude ambient",
        "heartbroken": "heartbreak breakup emotional ballad",

        # Calm / peaceful
        "calm": "calm peaceful ambient meditation",
        "relaxed": "relaxed chill lofi jazz",
        "sleepy": "sleep ambient drone soft piano",
        "peaceful": "peaceful nature acoustic guitar",

        # Energetic / intense
        "energetic": "energetic workout pump up high tempo",
        "angry": "angry aggressive metal hard rock",
        "motivated": "motivated gym grind hip hop",
        "powerful": "powerful epic orchestral cinematic",

        # Nostalgic / retro
        "nostalgic": "nostalgic throwback 90s classics",
        "retro": "retro vintage 80s synthwave",
        "sentimental": "sentimental memories slow oldies",

        # Romantic / social
        "romantic": "romantic love RnB slow jam",
        "flirty": "flirty smooth sensual groove",
        "heartwarming": "heartwarming wholesome acoustic folk",

        # Focus / work
        "focused": "focus deep work lofi concentration",
        "creative": "creative flow instrumental jazz",
        "studying": "study concentration classical piano",
        "productive": "productive morning routine uptempo",

        # Dark / introspective
        "dark": "dark moody atmospheric alternative",
        "anxious": "anxious tense cinematic strings",
        "reflective": "reflective introspective indie folk",
        "hopeful": "hopeful uplifting inspirational",

        # Party / social
        "party": "party dance club house",
        "summer": "summer beach vibes tropical",
        "confident": "confident swagger hip hop trap",

        # Relief / freedom
        "relieved": "relieved free uplifting celebratory indie",
        "free": "freedom uplifting euphoric indie pop",
    }

    query = mood_queries.get(mood.lower(), mood)
    query = query.replace(",", "").replace("-", " ").strip()

    async with httpx.AsyncClient() as client:
        response = await client.get(
            f"{SPOTIFY_API_URL}/search",
            headers={"Authorization": f"Bearer {access_token}"},
            params={
                "q": query,
                "type": "track",
                "limit": 10,
                "market": "FR",
            },
        )

        if response.status_code != 200:
            print(f"DEBUG Spotify search error: {response.status_code} - {response.text}")
            response.raise_for_status()

        data = response.json()
        tracks = data.get("tracks", {}).get("items", [])
        return [track["uri"] for track in tracks if track.get("uri")]